# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='user_name',
            new_name='user',
        ),
    ]
